### ISSUE TITLE
Interoperability issue with Android Gradle plugin 3

### ISSUE THREAD

**Issue by nyarlathotep77** [tomasbjerre/git-changelog-gradle-plugin#11]
I'm currently migrating our project to Android Studio 3 and the last pending issue is due to `git-changelog-gradle-plugin` raising the exception below:

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:gitChangeLog'.
> com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;`

Any help would be greatly appreciated please.

**Comment by tomasbjerre** [comment]
If you do `./gradlew build -i`, or `-d`, you should get more information.

**Comment by nyarlathotep77** [comment]
Thank you very much for your prompt reply.
Please find the logs below:

`> Task :app:gitChangeLog
11:39:35.929 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Task :app:gitChangeLog' started
11:39:35.931 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':app:gitChangeLog'
11:39:35.932 [INFO] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Putting task artifact state for task ':app:gitChangeLog' into context took 0.0 secs.
11:39:35.932 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':app:gitChangeLog' is up-to-date
11:39:35.932 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':app:gitChangeLog' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
11:39:35.933 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':app:gitChangeLog'.
11:39:35.933 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Execute task action 1/1 for :app:gitChangeLog' started
11:39:36.947 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.947 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.947 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.947 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.947 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.948 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 2
11:39:36.948 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.948 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.948 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.948 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.948 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 2
11:39:36.948 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 3
11:39:36.948 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 5
11:39:36.949 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 7
11:39:36.949 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 11
11:39:36.950 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 11
11:39:36.951 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 15
11:39:36.951 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 17
11:39:36.951 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 21
11:39:36.952 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 25
11:39:36.952 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 31
11:39:36.953 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 39
11:39:36.953 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 48
11:39:36.954 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 58
11:39:36.954 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 67
11:39:36.955 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 77
11:39:36.956 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 90
11:39:36.957 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 97
11:39:36.958 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 107
11:39:36.959 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 116
11:39:36.960 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 121
11:39:36.961 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 125
11:39:36.962 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 128
11:39:36.963 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 130
11:39:36.963 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 131
11:39:36.964 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 131
11:39:36.964 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 129
11:39:36.965 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 126
11:39:36.966 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 122
11:39:36.966 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 117
11:39:36.967 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 113
11:39:36.967 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 111
11:39:36.968 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 108
11:39:36.969 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 104
11:39:36.969 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 100
11:39:36.970 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 96
11:39:36.970 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 91
11:39:36.971 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 86
11:39:36.971 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 80
11:39:36.971 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 74
11:39:36.972 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 68
11:39:36.972 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 64
11:39:36.972 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 60
11:39:36.973 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 57
11:39:36.973 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 55
11:39:36.973 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 52
11:39:36.974 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 51
11:39:36.974 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 50
11:39:36.974 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 49
11:39:36.974 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 48
11:39:36.975 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 47
11:39:36.975 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 46
11:39:36.975 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 45
11:39:36.975 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 43
11:39:36.975 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 42
11:39:36.976 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 40
11:39:36.976 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 37
11:39:36.976 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 34
11:39:36.976 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 31
11:39:36.976 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 27
11:39:36.977 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 22
11:39:36.977 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 18
11:39:36.977 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 15
11:39:36.977 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 12
11:39:36.977 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 8
11:39:36.977 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 5
11:39:36.977 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 3
11:39:36.977 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.977 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 0
11:39:36.979 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.979 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.979 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.979 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.979 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.980 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 2
11:39:36.980 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.980 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.980 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.980 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.980 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 2
11:39:36.980 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 3
11:39:36.980 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 5
11:39:36.981 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 7
11:39:36.981 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 9
11:39:36.981 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 8
11:39:36.981 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 8
11:39:36.981 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 6
11:39:36.982 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 7
11:39:36.982 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 9
11:39:36.982 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 11
11:39:36.982 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 11
11:39:36.983 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 13
11:39:36.983 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 12
11:39:36.984 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 11
11:39:36.984 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 13
11:39:36.984 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 11
11:39:36.985 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 12
11:39:36.985 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 11
11:39:36.986 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 11
11:39:36.986 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 9
11:39:36.986 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 6
11:39:36.986 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 6
11:39:36.986 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 4
11:39:36.987 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 2
11:39:36.987 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.987 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 1
11:39:36.987 [DEBUG] [se.bjurr.gitchangelog.internal.git.GitRepo] Work left: 0
11:39:36.994 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Execute task action 1/1 for :app:gitChangeLog'
11:39:36.995 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
11:39:36.995 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':app:gitChangeLog'
11:39:37.001 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Task :app:gitChangeLog'
11:39:37.001 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor] 
11:39:37.001 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Task :app:gitChangeLog' completed
11:39:37.001 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :app:gitChangeLog (Thread[Task worker for ':' Thread 6,5,main]) completed. Took 1.073 secs.
11:39:37.001 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.87 completed (1 worker(s) in use)
11:39:37.001 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':' Thread 6: released lock on root.1.87
11:39:37.001 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':' Thread 6: released lock on :
11:39:37.002 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 6,5,main]] finished, busy: 1.073 secs, idle: 0.002 secs
11:39:37.002 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 2,5,main]] finished, busy: 0.0 secs, idle: 1.077 secs
11:39:37.002 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 5,5,main]] finished, busy: 0.0 secs, idle: 1.076 secs
11:39:37.002 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 4,5,main]] finished, busy: 0.0 secs, idle: 1.077 secs
11:39:37.002 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Daemon worker,5,main]] finished, busy: 0.0 secs, idle: 1.076 secs
11:39:37.002 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 3,5,main]] finished, busy: 0.0 secs, idle: 1.077 secs
11:39:37.002 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':',5,main]] finished, busy: 0.0 secs, idle: 1.077 secs
11:39:37.002 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 7,5,main]] finished, busy: 0.0 secs, idle: 1.076 secs
11:39:37.004 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
11:39:37.010 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:39:37.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:39:37.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:39:37.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:39:37.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':app:gitChangeLog'.
11:39:37.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
11:39:37.011 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:39:37.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
11:39:37.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:gitChangeLog'.
11:39:37.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
11:39:37.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
11:39:37.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
11:39:37.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
11:39:37.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
11:39:37.012 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
11:39:37.013 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NoSuchMethodError: com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at se.bjurr.gitchangelog.internal.settings.Settings.getCustomIssues(Settings.java:231)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at se.bjurr.gitchangelog.internal.settings.IssuesUtil.getIssues(IssuesUtil.java:19)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at se.bjurr.gitchangelog.internal.issues.IssueParser.parseForIssues(IssueParser.java:60)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:438)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:73)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:97)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:109)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at se.bjurr.gitchangelog.api.GitChangelogApi.toFile(GitChangelogApi.java:121)
11:39:37.014 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask.gitChangelogPluginTasks(GitChangelogTask.java:419)
11:39:37.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
11:39:37.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
11:39:37.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
11:39:37.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
11:39:37.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
11:39:37.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
11:39:37.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
11:39:37.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
11:39:37.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
11:39:37.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
11:39:37.015 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
11:39:37.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
11:39:37.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
11:39:37.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 27 more
11:39:37.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:39:37.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:39:37.016 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
11:39:37.016 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
11:39:37.017 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 9s`

**Comment by tomasbjerre** [comment]
You probably have some other plugin that adds another version of Guava on the classpath...

It can be fixed from my side by simply avoid using Guava.

**Comment by nyarlathotep77** [comment]
The only plugins I'm using are:
`apply plugin: 'org.greenrobot.greendao'
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'io.fabric'
apply plugin: "se.bjurr.gitchangelog.git-changelog-gradle-plugin"`

so nothing too exotic I think.

What would the fix on your side would imply?
If I can help with anything please let me know as I'd like to keep on using your plugin.

**Comment by tomasbjerre** [comment]
I would try to remove Guava from the lib:
https://github.com/tomasbjerre/git-changelog-lib/blob/master/build.gradle#L40

Or avoid using firstNonNull.

Then release and use that new lib version in this plugin.

**Comment by nyarlathotep77** [comment]
Thank you so much for caring! 👍

**Comment by tomasbjerre** [comment]
You may try version 1.52 now. It does not use Guava Objects.

**Comment by nyarlathotep77** [comment]
Just tried and it worked.
Thank you ever so much for such a hyper-fast fix to a problem reported just by me.
