### ISSUE TITLE
Feature request: Clickable link to JIRA issue

### ISSUE THREAD

**Issue by DPUkyle** [tomasbjerre/git-changelog-gradle-plugin#12]
Hi Tomas, the Task type defined in this plugin is quite useful. Thank you.

Perhaps this an enhancement for `git-changelog-lib` and not this plugin, but how difficult would it be to make the link to jira clickable when the `jiraServer` property is set? I imagine it is just a simple concatenation of `getJiraServer().concat("/browse/").concat(issueId)`. To make that label clickable directly from the generated changelog would be pretty cool.

**Comment by tomasbjerre** [comment]
When jiraServer is specified you will have the issueLink populated. And it is up to you to create a link in your template.

**Comment by DPUkyle** [comment]
OK thanks Tomas, I'll give it a shot.
