### ISSUE TITLE
ignoreTagsIfNameMatches is not working

### ISSUE THREAD

**Issue by muzammil786** [tomasbjerre/git-changelog-gradle-plugin#14]
I have a tag which I want to ignore in the changelog. The tag name is MobileGateway_19.04.35. I am using the regex below

ignoreTagsIfNameMatches = 'MobileGateway.*'

But this still produces the tag. I have also tried

ignoreTagsIfNameMatches = 'MobileGateway_19.04.35'
 
But still does not work.

Do I have to enable any other settings, or is it a bug?

**Comment by tomasbjerre** [comment]
Perhaps `ignoreTagsIfNameMatches = '.*MobileGateway.*'`?

**Comment by muzammil786** [comment]
That worked. Thanks.

Just wondering what is wrong with 'MobileGateway.*' ?

Especially when we want to search from the start of the tag.

**Comment by tomasbjerre** [comment]
It is matched against `refs/heads/MobileGateway`. That is how it is read from Git... So this should also work: `refs/heads/MobileGateway.*`
