### ISSUE TITLE
a way to filter commits with certain word in its title into changelog group?

### ISSUE THREAD

**Issue by ROMVoid95** [tomasbjerre/git-changelog-gradle-plugin#23]
I use a commit template for my commits which start with certain words: Example
`Add: ability to teleport`
`Fix: crash when  joining server`

is there a way to filter those commits to generate a changelog like this?

```markdown
[Added]
 - ability to teleport

[Fixes]
 - crash when joining server
```

**Comment by tomasbjerre** [comment]
Not possible now, but can be added, pull requests are welcome.

**Comment by ROMVoid95** [comment]
oh i am so new to groovy its not funny, but ill fork and play around with it to learn and make a pr if im able too. Guess i should ask if its best to implement this in the `git-changelog-lib` repo or this repo?

**Comment by tomasbjerre** [comment]
should be possible now, using helpers. See readme.
