### ISSUE TITLE
Error creating md file. It creates as directory

### ISSUE THREAD

**Issue by secoga** [tomasbjerre/git-changelog-gradle-plugin#26]
Hi, 

This week creating new release notes I got the following error:  `java.nio.file.FileSystemException: foo/bar/CHANGELOG_1_0_25.md: Is a directory`

Reviewing the workspaces there were create the `CHANGELOG_1_0_25.md` as directory instead of a file. Using the last version of your library and `gradle 4.5`. The last time that it succeded there were running version `se.bjurr.gitchangelog:git-changelog-gradle-plugin:1.66` so I've changed to that version and the file has been created as usual. 

There could be an unsupported feature between my current gradle versión and your last version?

Thanks for you work guys!!

Kind Regards,

Sergio

**Comment by tomasbjerre** [comment]
Thanks for reporting. Should be fixed now!
