### ISSUE TITLE
changelog failing to generate on jenkins

### ISSUE THREAD

**Issue by dmodoomsirius** [tomasbjerre/git-changelog-gradle-plugin#31]
when using se.bjurr.gitchangelog.git-changelog-gradle-plugin" version "1.72.0 
https://github.com/Advanced-Rocketry/libVulpes/blob/1.16.5/build.gradle the changelog is failing to generate on jenkins 

http://jenkins.dmodoomsirius.me/job/LibVulpes/job/1.16.5/7/console

any guidance would be greatly appreciated.

**Comment by tomasbjerre** [comment]
Does it work with ./gradlew build --no-daemon ?

**Comment by dmodoomsirius** [comment]
http://jenkins.dmodoomsirius.me/job/LibVulpes/job/1.16.5/8/console it worked with the --no-daemon

**Comment by dmodoomsirius** [comment]
http://maven.dmodoomsirius.me/zmaster587/libVulpes/libVulpes/1.16.5-1.0.2-8/libVulpes-1.16.5-1.0.2-8-changelog.html
