### ISSUE TITLE
Changelog does not show latest tags, when Version Scheme x.y.z has been changed to x.y only

### ISSUE THREAD

**Issue by manticore-projects** [tomasbjerre/git-changelog-gradle-plugin#35]
Greetings.

For reference: https://github.com/JSQLParser/JSqlParser
Unfortunately, the version tags have been changed from x.y.z to only x.y since `jsqlparser-0.9.7`:

```shell
are@archlinux ~/d/s/J/JSQLParser (sphinx)> git -P tag
jsqlparser-0.8.4
jsqlparser-0.8.5
...
jsqlparser-0.9.4
jsqlparser-0.9.5
jsqlparser-0.9.6
jsqlparser-0.9.7
jsqlparser-1.0
jsqlparser-1.1
...
jsqlparser-4.4
jsqlparser-4.5
```

When creating a Changelog, the tags stop exactly at `0.9.7` and ignore any later tags. All changes since `0.9.7` are shown under `Latest Changes`:

![image](https://user-images.githubusercontent.com/18080123/185749497-eaa3cbef-dad9-4092-825f-d1998f65d4c3.png)

Please what can be done about that? Unfortunately I am not the owner of JSQLParser and so can no rename the Tags (permanently).
Also, I do believe that the approach is somewhat ugly, but not invalid.

Thanks a lot in advance and cheers!

PS: Remarks containing single quotes `'` come out garbled, you can see that in the screenshot:
```
Show the Statement&#x27;s Java Objects in a tree hierarchy
```

**Comment by tomasbjerre** [comment]
You can supply your own custom template to include all tags, perhaps this:
https://github.com/tomasbjerre/git-changelog-lib#template---simple

The default template is the one based on conventional commits:
https://github.com/tomasbjerre/git-changelog-lib#template---conventional

It will filter out the none semantic versions because of the `{{#ifReleaseTag .}}`.

**Comment by manticore-projects** [comment]
> It will filter out the none semantic versions because of the `{{#ifReleaseTag .}}`.

Thank you, removing this did the trick!
