### ISSUE TITLE
How to limit the Changelog to the N latest Tags only

### ISSUE THREAD

**Issue by manticore-projects** [tomasbjerre/git-changelog-gradle-plugin#36]
Greetings.

How would I limit the Changelog to the last N Tags, e.g. showing only the latest 5 releases?
I have some very old Projects starting around 2002 generating some epic Changelogs, which need to be trimmed.

Thank you in advance and cheers!

**Comment by tomasbjerre** [comment]
If you are using a scripted pipeline, you can determine that tag with a shellcript:
https://stackoverflow.com/questions/30805098/how-to-display-last-n-tags-in-git

One alternative may also be to look at git shallow clone and clone depth. Let Git clone just the part you want included and this plugin will only operate on that.

**Comment by manticore-projects** [comment]
Thank you so much for prompt response.
Pardon me to be blunt: it seems to be easier to call Gradle per exec directly and to mangle its output. I was hoping the plugin would make it easier.

**Comment by manticore-projects** [comment]
Greetings.

I have eventually figured a solution for my needs:

```gradle
task gitChangelogTask(type: GitChangelogTask) {
    fromRepo = file("$projectDir")
    file = new File("${projectDir}/src/site/sphinx/changelog.rst")
    fromRef = "4.0";
    //toRef = "1.1";
    templateContent ="""
************************
Changelog
************************


{{#tags}}
Version {{name}}
=============================================================

 {{#issues}}

  {{#commits}}
   {{#ifMatches messageTitle "^(?!Merge).*"}}
  * **{{messageTitle}}** - {{authorName}}
   {{/ifMatches}}
  {{/commits}}

 {{/issues}}
{{/tags}}
"""
}
```
The `fromRef` did the trick.
