### ISSUE TITLE
Support for Kotlin DSL

### ISSUE THREAD

**Issue by almogtavor** [tomasbjerre/git-changelog-gradle-plugin#38]
Hey
I've tried using the plugin within Gradle's Kotlin DSL and I couldn't manage to do that. Is it possible & supported?
If so, I'd like to get an example, which I think should get added to the README.md

**Comment by tomasbjerre** [comment]
See https://github.com/tomasbjerre/git-changelog-gradle-plugin/blob/master/git-changelog-gradle-plugin-example-kotlin/build.gradle.kts

**Comment by almogtavor** [comment]
@tomasbjerre Thanks!
