### ISSUE TITLE
Can you please added example to generate next tag

### ISSUE THREAD

**Issue by gauravjeswani** [tomasbjerre/git-changelog-gradle-plugin#39]
Can you please added example to generate next tag?

I tried from README, but it's not working out somehow for me. May be due to lack of understanding of this. If would be great, if you can provide some working example to generate next tag.

**Comment by tomasbjerre** [comment]
Perhaps you can find something here https://github.com/tomasbjerre/gradle-scripts/blob/master/src/main/resources/main.gradle
