### ISSUE TITLE
Incompatible with Gradle 7.6

### ISSUE THREAD

**Issue by mklueh** [tomasbjerre/git-changelog-gradle-plugin#40]
Hello,

it seems this plugin is not compatible with Gradle 7.6 anymore.

This is the error I'm now getting
> Value is null

with my configuration

```
task generateChangelog(type: GitChangelogTask) {
    fromRepo = file(".");
    prependToFile = false;
    file = file("CHANGELOG.md")
    templateContent = file('changelog.mustache').getText('UTF-8');
}
```

**Comment by tomasbjerre** [comment]
Change `fromRepo = file(".");` to `fromRepo = new File(".");`.
