### ISSUE TITLE
Using with axion-release-plugin

### ISSUE THREAD

**Issue by rinmalavi** [tomasbjerre/git-changelog-gradle-plugin#45]
Trying to automate CI with [axion-release-plugin](https://github.com/allegro/axion-release-plugin)
and generate CL and calc next version with `git-changelog-gradle-plugin`.

In `pre` stage of axion-release-plugin/release task, which is just before tagging, i would like to have CL generated so that the script could commit it with the updated project version( removed "-SNAPSHOT", used `getNextSemanticVersion`).

I understand CL versions are read from git tags.
Is there a way to tell `gitChangelogTask` what version the last commit should be, and what tag(version) before commit/tag with this change.

(Maybe going about this the wrong way)

**Comment by tomasbjerre** [comment]
In such a case it might be easier to just use the library:
https://github.com/tomasbjerre/git-changelog-lib

You can get next semantic version with:

```
def nextVersion = gitChangelogApiBuilder()
  .withSemanticMajorVersionPattern("^[Bb]reaking")
  .withSemanticMinorVersionPattern("[Ff]eature")
  .getNextSemanticVersion();

println "Next version:" + nextVersion.toString();
println " Major:" + nextVersion.getMajor();
println " Minor:" + nextVersion.getMinor();
println " Patch:" + nextVersion.getPatch();
println " Tag:" + nextVersion.findTag().get();
```
There is also a `getHighestSemanticVersion()` to get previous released version.

And you can prepend to the changelog with:

```
import static se.bjurr.gitchangelog.api.GitChangelogApi.gitChangelogApiBuilder;
gitChangelogApiBuilder() //
  .withFromRef(highestVersion.findTag().get()) //
  .withToRef("master")
  .prependToFile("CHANGELOG.md");
```

Perhaps you want to check how the library is being used here in the plugin:
https://github.com/tomasbjerre/git-changelog-gradle-plugin/blob/master/src/main/java/se/bjurr/gitchangelog/plugin/gradle/GitChangelogTask.java

**Comment by rinmalavi** [comment]
Yep, did something similar,
thanks!
