### ISSUE TITLE
Get Next Release gradle task gets error "Did not find GIT repo in /data/1/.gradle/daemon/8.7/"

### ISSUE THREAD

**Issue by csirwin** [tomasbjerre/git-changelog-gradle-plugin#50]
I am trying to create a gradle task that will get the next release but when I run this gradle task:
```
tasks.register('getNextSeamticRelease') {
  def nextVersion = se.bjurr.gitchangelog.api.GitChangelogApi.gitChangelogApiBuilder()
   .withSemanticMajorVersionPattern("^[Bb]reaking")
   .withSemanticMinorVersionPattern("[Ff]eature")
   .getNextSemanticVersion();

  println "Next version:" + nextVersion.toString();
  println " Major:" + nextVersion.getMajor();
  println " Minor:" + nextVersion.getMinor();
  println " Patch:" + nextVersion.getPatch();
}
```
I set where the error occurs in git-changelog-lib but I can't figure out how to set the GitRepo directory like I do for the GitChangeLogTask via the "fromRepo" property

**Comment by tomasbjerre** [comment]
I do it like this: https://github.com/tomasbjerre/gradle-scripts/blob/3122ccd8a35e6f796fdda1ed52e9b9fdcf563eb7/src/main/resources/main.gradle#L428

**Comment by csirwin** [comment]
awesome, thanks!
