### ISSUE TITLE
Sudden JDK 17 dependency?!

### ISSUE THREAD

**Issue by manticore-projects** [tomasbjerre/git-changelog-gradle-plugin#52]
Greetings!

```
se.bjurr.gitchangelog.git-changelog-gradle-plugin.gradle.plugin:2.2.2
Dependency requires at least JVM runtime version 17. This build uses a Java 11 JVM.
```

I did not find any mentioning of this new requirement and such a step would warrant a new major release also?
Is it a mistake or a feature?

**Comment by tomasbjerre** [comment]
It is 17 because Handlebars is 17.

**Comment by manticore-projects** [comment]
Greetings! Thank you for your response.

I don't have a problem with the JDK 17 requirement itself, but how it has been handled -- especially on a plugin for SEMVER:

1) maybe put  some explanation into the README, pointing on the last JDK 11 compliant version
2) maybe increase the major version -- because this is a breaking change

**Comment by tomasbjerre** [comment]
Can you actually use the 2.2.2 version? I am struggling with getting the packaging right with some new build scripts.

**Comment by manticore-projects** [comment]
Previously my gradle line looked like this:
```groovy
id "se.bjurr.gitchangelog.git-changelog-gradle-plugin" version "latest.version"
```

Now I have had to change it into this:
```groovy
id "se.bjurr.gitchangelog.git-changelog-gradle-plugin" version "2.0.0" //later depends on JDK 17
```

Interestingly 2.1 or 2.1.1 also did not work because "not found" messages.
And 2.2.2 does not work for me because I insist in a JDK 11 build (do to using the XMLDoclet).

**Comment by tomasbjerre** [comment]
I'm also getting the "not found" with those versions. The marker artifact is here:
https://plugins.gradle.org/m2/se/bjurr/gitchangelog/git-changelog-gradle-plugin/se.bjurr.gitchangelog.git-changelog-gradle-plugin.gradle.plugin/2.2.2/se.bjurr.gitchangelog.git-changelog-gradle-plugin.gradle.plugin-2.2.2.pom
And that pom points to:
https://plugins.gradle.org/m2/se/bjurr/gitchangelog/git-changelog-gradle-plugin/2.2.2/

Older versions:
https://plugins.gradle.org/m2/se/bjurr/gitchangelog/git-changelog-gradle-plugin/se.bjurr.gitchangelog.git-changelog-gradle-plugin.gradle.plugin/2.0.0/se.bjurr.gitchangelog.git-changelog-gradle-plugin.gradle.plugin-2.0.0.pom
Points to a `groupId` starting with `gradle.plugin.se....`:
https://plugins.gradle.org/m2/gradle/plugin/se/bjurr/gitchangelog/git-changelog-gradle-plugin/2.0.0/

Regarding the Java 17 requirement. Perhaps best to do what Handlebars did and mention it in the readme (https://github.com/jknack/handlebars.java) and also, like you said, the changelog.

**Comment by tomasbjerre** [comment]
Added compatibility to readme.

**Comment by tomasbjerre** [comment]
I asked about the "not found" issue here:
https://discuss.gradle.org/t/using-a-released-plugin-when-building-the-same-plugin-causes-error/49554

It may help to do this i `settings.gradle`
```groovy
plugins {
	id "se.bjurr.gitchangelog.git-changelog-gradle-plugin" version "2.2.1" apply false
}
```

And in `build.gradle`:
```groovy
plugins {
	id "se.bjurr.gitchangelog.git-changelog-gradle-plugin"
}
```
