### ISSUE TITLE
Error when there is no master branch.

### ISSUE THREAD

**Issue by dmodoomsirius** [tomasbjerre/git-changelog-gradle-plugin#6]
https://gist.github.com/dmodoomsirius/510dbdce773533f58d7731aeed932fa4

Build.gradle https://github.com/BuiltBrokenModding/ICBM-Classic/blob/development/build.gradle
gradle.properties https://github.com/BuiltBrokenModding/ICBM-Classic/blob/development/gradle.properties

**Comment by tomasbjerre** [comment]
What if you [try 1.40](https://github.com/BuiltBrokenModding/ICBM-Classic/blob/development/build.gradle#L25) of the plugin?

This should have been solved in https://github.com/tomasbjerre/git-changelog-lib/issues/28
