### ISSUE TITLE
Relative paths for files aren't always right..

### ISSUE THREAD

**Issue by jonathansloman** [tomasbjerre/git-changelog-gradle-plugin#7]
Because you're using 'new File()'... rather than file(), the current working directory for relative paths is not always right. I envoke gradle within eclipse using buildship, and all the relative files are then relative to the directory eclipse was run in, rather than the project directory.

If you use file() instead this should fix it. See https://docs.gradle.org/3.0/userguide/working_with_files.html

**Comment by tomasbjerre** [comment]
This is just in the examples right? Should be fixed now.

**Comment by jonathansloman** [comment]
Hi - sorry I should have been more clear, not it's not just in the examples. It's also an issue with how the settings file is passed through if you use it, eg I had to have the following for it to find it:
      settingsFile = file("changelog.json").absolutePath;
because in your code you do:
    builder.withSettings(new File(settingsFile).toURI().toURL());

Also I think there may be a problem with fromRepo - thank you for adding that as an exposed setting. However the path is being passed directly through to the underlying library here:
  builder.withFromRepo(fromRepo); 
(incidentally, shouldn't this have an isSupplied(fromRepo) conditional around it?).

Then looking in GitChangelogApi.java in the library project, that gets used as: 
      try (GitRepo gitRepo = new GitRepo(new File(this.settings.getFromRepo()))) {

so it's likely to get hit with the same problem of potentially using the wrong current working directory for relative paths.

Obviously you can't use the gradle file() in the java library, so maybe the gradle code needs to do something like
 builder.withFromRepo(file(fromRepo).absolutePath)
though it's a bit ugly.

Thanks for looking at this!

**Comment by tomasbjerre** [comment]
The `getFromRepo` defaults to ".". It did that before and now also, so if not supplied i believe it will work just like before.

Is your usage of `file("changelog.json").absolutePath;` not a working solution for you? Or you mean that it can be done prettier?

**Comment by jonathansloman** [comment]
but you weren't calling builder.withFromRepo at all before - now you're calling it whether or not fromRepo has been set - you need to not call it if fromRepo hasn't been set to get the old default behaviour I think?

It is a working solution, but it's likely to cause other people a headache wondering what's going on - if you could change  it to:
  builder.withSettings(file(settingsFile).toURI().toURL()
then it will be both prettier and less likely to cause others issues.

Thanks again, it is appreciated.

**Comment by tomasbjerre** [comment]
Here is how it is read in the library:
https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/main/java/se/bjurr/gitchangelog/internal/settings/Settings.java#L192
So if the gradle plugin is setting it to null, then it should default to ".".

This is the line you want to change right?
https://github.com/tomasbjerre/git-changelog-gradle-plugin/blob/master/src/main/java/se/bjurr/gitchangelog/plugin/gradle/GitChangelogTask.java#L317
Only problem is that that is Java-code =)

**Comment by jonathansloman** [comment]
Ah okay, I hadn't gone through to the library to see that it coped with a null fromRepo being set, makes sense.

Argh, yes of course that's java code, sorry I wasn't thinking.

I'm not a gradle plugin expert, but I went hunting and found this:
 https://docs.gradle.org/current/userguide/custom_plugins.html

specifically the section 41.4
so would:
  build.withSettings(getProject().file(settingsFile).toURI().toURIL();
work?

**Comment by tomasbjerre** [comment]
Ok! Should be fixed now in 1.47! Open issue again if not working

**Comment by jonathansloman** [comment]
Thanks - it's working. I did find one other place with the same file issue though - the filePath option for specifying where the changelog goes. This is just passed through as a string to the underlying library, so the only workaround is to do:
  filePath = file('...desired path...').absolutePath
but it could be fixed by doing that in your plugin code. Alternately you may want to update your examples to do the above. Up to you.
