### ISSUE TITLE
fromRepo not exposed

### ISSUE THREAD

**Issue by jonathansloman** [tomasbjerre/git-changelog-gradle-plugin#8]
Hi,
It looks like the setting 'fromRepo' is not exposed in the plugin. 

For various reasons, we often have multiple projects within a single repository. We'd like to be able to generate a changelog for a given project, which requires the changelog task to know that  its associated git repository is actually in a parent directory, not the current directory. The fromRepo setting in the underlying library allows this, but isn't exposed in the plugin. You can set it in the json setting files, but then hit the issue of relative paths being wrong depending on how gradle is launched, and specifying it as an absolute path is all kinds of wrong.

**Comment by tomasbjerre** [comment]
Added and released, open issue again if not working.
